# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(874, 755)
        MainWindow.setStyleSheet("backgroud-color:rgb(255, 255, 127);\n"
"color: green;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.title = QtWidgets.QLabel(self.centralwidget)
        self.title.setGeometry(QtCore.QRect(260, 180, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(14)
        self.title.setFont(font)
        self.title.setStyleSheet("backgroud-color:rgb(85, 255, 0)")
        self.title.setObjectName("title")
        self.result = QtWidgets.QLabel(self.centralwidget)
        self.result.setGeometry(QtCore.QRect(140, 250, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Mongolian Baiti")
        font.setPointSize(12)
        self.result.setFont(font)
        self.result.setObjectName("result")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(320, 450, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: violet;\n"
" background-color: red; ")
        self.pushButton.setObjectName("pushButton")
        self.cd_alphabet = QtWidgets.QCheckBox(self.centralwidget)
        self.cd_alphabet.setGeometry(QtCore.QRect(240, 320, 291, 61))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        self.cd_alphabet.setFont(font)
        self.cd_alphabet.setStyleSheet("backgroud-color: rgb(0, 170, 0);")
        self.cd_alphabet.setObjectName("cd_alphabet")
        self.cd_numbers = QtWidgets.QCheckBox(self.centralwidget)
        self.cd_numbers.setGeometry(QtCore.QRect(240, 380, 291, 51))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(12)
        self.cd_numbers.setFont(font)
        self.cd_numbers.setObjectName("cd_numbers")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.title.setText(_translate("MainWindow", "    Генератор паролів"))
        self.result.setText(_translate("MainWindow", "    Тут буде результат "))
        self.pushButton.setText(_translate("MainWindow", "Згенерувати "))
        self.cd_alphabet.setText(_translate("MainWindow", "  Використовавати числа"))
        self.cd_numbers.setText(_translate("MainWindow", "Використовувати алфавіт "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
